# Calculating NearestNeighbour

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
import sys
import time
import math

In [39]:
cities = pd.read_csv('data/cities.csv')
ids = cities.CityId.values[1:]
xy = np.array([cities.X.values, cities.Y.values]).T[1:]
path = [0,]

In [4]:
xy

array([[ 4377.40597217,   336.60208217],
       [ 3454.15819771,  2820.05301125],
       [ 4688.09929763,  2935.89805581],
       ..., 
       [ 4775.8898741 ,  3103.84622792],
       [ 2994.23095453,  1931.76434369],
       [ 1354.7647783 ,  3218.10062536]])

In [40]:
ids

array([     1,      2,      3, ..., 197766, 197767, 197768], dtype=int64)

In [41]:
ids = np.delete (ids, 2, axis=0)
ids

array([     1,      2,      4, ..., 197766, 197767, 197768], dtype=int64)

In [8]:
last_x, last_y = cities.X[path[-1]], cities.Y[path[-1]]
dist = ((xy - np.array([last_x, last_y]))**2).sum(-1)

In [10]:
last_x

316.83673906150904

In [11]:
dist

array([ 19969203.11426561,  10224354.42531243,  19646042.73948573, ...,
        20695867.06475597,   7241651.35358993,   2109062.82571657])

In [12]:
nearest_index = dist.argmin()
nearest_index

78933